CREATE TABLE login(
id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
cpf VARCHAR(11) NOT NULL,
login VARCHAR(32) NOT NULL,
senha VARCHAR(32) NOT NULL
);


CREATE TABLE paciente(
id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
id_login INT NOT NULL,
id_endereco INT NOT NULL,
id_contato INT NOT NULL,
nome VARCHAR(64) NOT NULL
FOREIGN KEY(id_login) REFERENCES login(id),
FOREIGN KEY(id_enfereco) REFERENCES endereco(id),
FOREIGN KEY(id_contato) REFERENCES contato(id)
);

CREATE TABLE medico(
id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
id_login INT NOT NULL,
id_especialidade INT NOT NULL,
nome VARCHAR(64) NOT NULL,
FOREIGN KEY(id_login) REFERENCES login(id),
FOREIGN KEY(id_especialidade) REFERENCES especialidade(id)
);

CREATE TABLE especialidades(
id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
nome VARCHAR(64) NOT NULL
);

CREATE TABLE endereco(
id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
CEP INT(11) NOT NULL,
pais VARCHAR(32) NOT NULL,
UF VARCHAR(2) NOT NULL,
cidade VARCHAR(32) NOT NULL,
bairro VARCHAR(32) NOT NULL,
logradouro VARCHAR(32) NOT NULL,
numero VARCHAR(6) NOT NULL,
complemento VARCHAR(64) NOT NULL
);

CREATE TABLE contato(
id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
email VARCHAR(64) NOT NULL,
celular_1 INT(13) NOT NULL,
celular_2 INT(13) NOT NULL,
);

CREATE TABLE agendamento(
id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
ativa BOOL(1) NOT NULL,
data_hora DATETIME NOT NULL,
id_medico INT NOT NULL,
id_paciente INT NOT NULL,
tipo_agendamento ENUM('1', '2') NOT NULL,
FOREIGN KEY(id_medico) REFERENCES medico(id) NOT NULL,
FOREIGN KEY(id_paciente) REFERENCES paciente(id) NOT NULL,
);